go.mod, main.go, website/docs/r/environment.html.markdown
This PR documents the client_side_id attribute as requested in terraform-providers/terraform-provider-launchdarkly#1
=> Document client_side_id (#35)

go.mod
As per other Terraform providers, the module path should include `github.com/terraform-providers` as a prefix.
=> Change module path to include full source path

CHANGELOG.md, launchdarkly/config.go, launchdarkly/resource_launchdarkly_feature_flag.go, launchdarkly/validation_helper.go, website/docs/d/team_member.html.markdown, website/docs/r/environment.html.markdown, website/docs/r/feature_flag.html.markdown, website/docs/r/team_member.html.markdown
This PR adds basic input validation to the the `resource_launchdarkly_feature_flag` `maintainer_id` argument. The website documentation has also been updated to further clarify this attribute.
```
=== RUN   TestCleanAccount
--- SKIP: TestCleanAccount (0.00s)
=== RUN   TestCustomPropertiesRoundTripConversion
=== RUN   TestCustomPropertiesRoundTripConversion/basic_custom_property
=== RUN   TestCustomPropertiesRoundTripConversion/Multiple_custom_properties
--- PASS: TestCustomPropertiesRoundTripConversion (0.00s)
--- PASS: TestCustomPropertiesRoundTripConversion/basic_custom_property (0.00s)
--- PASS: TestCustomPropertiesRoundTripConversion/Multiple_custom_properties (0.00s)
=== RUN   TestAccDataSourceTeamMember_noMatchReturnsError
=== PAUSE TestAccDataSourceTeamMember_noMatchReturnsError …
```
=> Add mainter_id validation

website/docs/r/feature_flag_environment.html.markdown
The rollout weights documentation listed the required sum to be
1,000,000 but it's actual 100,000
=> Fix: rollout weights documentation.

CHANGELOG.md, launchdarkly/project_helper.go, launchdarkly/resource_launchdarkly_flag_trigger.go, launchdarkly/resource_launchdarkly_flag_trigger_test.go, launchdarkly/segment_rule_helper.go, launchdarkly/segment_rule_helper_test.go, website/docs/r/segment.html.markdown
BUG FIXES:
- Fixed a [bug](https://app.shortcut.com/launchdarkly/story/138913/terraform-provider-panics-when-trying-to-create-triggers-that-are-enabled) preventing `launchdarkly_flag_trigger`s from being created in the `enabled` state.
- Fixed a [bug](https://github.com/launchdarkly/terraform-provider-launchdarkly/issues/79) introduced in v2.2.0 where `launchdarkly_segments` with `rule` blocks not containing a `weight` were defaulting to a `weight` of 0.
=> Prepare 2.4.1 release

.circleci/config.yml
Somehow we ended up with the `CHECKPOINT_TIMEOUT` twice in our CIrcle config.
=> Fix merge issue in Circle config

website/docs/d/feature_flag.html.markdown, website/docs/d/project.html.markdown, website/docs/r/feature_flag.html.markdown, website/docs/r/project.html.markdown
This fixes links to these anchors from earlier in each page.
=> Fix typo in multiple docs headers

.circleci/config.yml, .gitattributes, .github/workflows/generate_integration_config_pr.yml, CHANGELOG.md, CODEOWNERS, GNUmakefile, launchdarkly/audit_log_subscription_configs_generated.go, launchdarkly/clause_helper.go, launchdarkly/data_source_launchdarkly_team_member_test.go, launchdarkly/data_source_launchdarkly_team_members_test.go, launchdarkly/resource_launchdarkly_feature_flag_environment.go, launchdarkly/resource_launchdarkly_feature_flag_environment_test.go, launchdarkly/resource_launchdarkly_feature_flag_test.go, launchdarkly/resource_launchdarkly_team_member_test.go, launchdarkly/resource_launchdarkly_team_test.go
BUG FIXES:
- Fixes a bug in the `launchdarkly_feature_flag_environment` that prevented users from updating targeting rule clauses when the targeting rule was being used as the fallthrough variation with a percentage rollout.
- Fixes a bug in the `launchdarkly_feature_flag_environment` that resulted in the default `string` rule clause value type not being respected. [#102](https://github.com/launchdarkly/terraform-provider-launchdarkly/issues/102)
=> prepare v2.9.1 release

CHANGELOG.md, launchdarkly/default_variations_helper.go, launchdarkly/default_variations_helper_test.go, launchdarkly/resource_launchdarkly_feature_flag_test.go
BUG FIXES:
- Fixes a bug in the `launchdarkly_feature_flag` resource where explicit defaults were not getting set for boolean flags upon creation.
=> Prepare v2.9.2 release

CHANGELOG.md, website/docs/r/team_member.html.markdown, website/launchdarkly.erb
This adds the `ignore_changes` guide to the sidebar so that it actually appears in the generated Terraform documentation, and adds the `Enterprise plan` note to the `account_members` resource. Also preps for 2.9.4 release to publish the docs.
=> [SC-174121] Docs bug fixes

docs/resources/webhook.md, templates/resources/webhook.md
This removes a duplicate `resources =` from the second statement in the launchdarkly_webhook example code.
It also formats the HCL for this example.
=> Fix typo in webhook example code

docs/data-sources/segment.md, launchdarkly/keys.go, launchdarkly/resource_launchdarkly_segment.go, launchdarkly/resource_launchdarkly_segment_test.go, launchdarkly/segments_helper.go
Map additional fields required for provider to support BigSegments.
**Testing**
For any changes you make, please ensure your acceptance test conform to the following:
- every single new attribute is tested
- optional attributes revert to null or default values if removed
- attributes that interact interact as expected
- block values behave as expected when reordered
- nested fields on maps or list/set items function as expected. Terraform does not actually enforce most schema attributes on nested items
- each test step for a configuration is followed by a test step where `ImportState` and `ImportStateVerify` are set to true. `ImportStateVerifyIgnore` can be used if we explicitly _expect_ a value to be different when imported, such as in the case of obfuscated values like API keys
For more …
=> Map additional fields for BigSegments.

docs/data-sources/environment.md, docs/resources/environment.md, docs/resources/project.md, launchdarkly/approvals_helper.go, launchdarkly/environments_helper_test.go, launchdarkly/keys.go
Hello!
This pull request will add support for setting `service_kind` and `service_config` in the approval settings on the project and environment resoures.
It will close #190
=> Add service kind and config to approval settings

terraform-registry-manifest.json
This PR adds the `terraform-registry-manifest` per the official documentation [here](https://github.com/launchdarkly/terraform-provider-launchdarkly/pull/new/hbarrow/REL-4482/add-terraform-registry-manifest-file):
> `protocol_versions`: List of strings with supported Terraform protocol versions of the provider. Providers developed using [Terraform Plugin SDK version 2](https://developer.hashicorp.com/terraform/plugin/sdkv2) should set this field to ["5.0"]. Providers developed using [Terraform Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework) should set this field to ["6.0"] unless the Framework is [explicitly configured for protocol version 5](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/providerserver#ServeOpts.ProtocolVersion). Defaults …
=> Add Terraform registry manifest file

.github/workflows/lint-pr-title.yml
This PR adds https://github.com/amannn/action-semantic-pull-request as a pre-cursor to using Release Please on this repository.
=> chore: add GHA to validate semantic pull request titles

.github/workflows/release.yml, .goreleaser.yml
This should set up the necessary release.yml and .goreleaser.yml files to push to the Terraform registry once we've tagged a new version.
=> chore: set up goreleaser

.github/workflows/test.yml
This PR sets up Technique 1 of the [Slack Send Github Action](https://github.com/slackapi/slack-github-action). This will send a webhook to invoke a Slack Workflow that will send a message to our project channel.
=> chore: send Slack notifications when acceptance tests fail on `main`

launchdarkly/resource_launchdarkly_team_test.go
This test keeps failing on our Github validation tests due to bad cleanup from previous runs causing a name conflict on the custom role. This adds some random characters to the name of the afflicted role to prevent future conflicts.
=> fix: add random characters to name that keeps conflicting

CHANGELOG.md
This PR removes a few duplicate change log entries that were created from failed releases.
=> chore: remove duplicate change log entries

docs/data-sources/metric.md, launchdarkly/metrics_helper.go
Separating this out into a separate PR from [this one](https://github.com/launchdarkly/terraform-provider-launchdarkly/pull/283). Once we upgrade the LD client to v17 and switch out the experiments beta api for the non-beta one, this field would cause a breaking change if not set to computed. Since it is deprecated, it should be harmless.
=> fix: make deprecated metric is_active field optional and computed

release-please-config.json
This PR changes the release-please configuration to open release PRs in draft mode. This should make our lives slightly easier as our Github Actions should run when we press "Ready for Review."
=> chore: configure release-please to open PRs in draft mode

docs/data-sources/feature_flag_environment.md, docs/resources/feature_flag_environment.md, examples/resources/launchdarkly_feature_flag_environment/resource.tf, launchdarkly/data_source_launchdarkly_feature_flag_environment_test.go, launchdarkly/fallthrough_helper.go, launchdarkly/resource_launchdarkly_feature_flag_environment_test.go, launchdarkly/rollout_helper.go, launchdarkly/rule_helper.go, launchdarkly/rule_helper_test.go
This PR adds the ability to specify the context kind used in a targeting rule's percentage rollout. This was requested in #265.
Testing:
- Added unit tests for functions in `rule_helper.go`
- Modified a couple of our existing acceptance tests to take advantage of this new attribute. I also 
- Manual
I used the following config:
```hcl
resource "launchdarkly_feature_flag_environment" "test_flag_environment" {
flag_id = launchdarkly_feature_flag.test_flag.id
env_key = "prod"
on      = true
rules {
clauses {
attribute = "country"
op        = "in"
values    = ["uk"]
}
rollout_weights = [60000, 40000]
bucket_by       = "country"
context_kind    = "account"
}
fallthrough {
variation = 1
}
off_variation = 1
}
```
=> feat: add context_kind to targeting rules with percentage rollouts

launchdarkly/environments_helper.go, launchdarkly/resource_launchdarkly_environment.go, launchdarkly/resource_launchdarkly_environment_test.go
This PR fixes a bug brought to our attention by a customer via the Support team where the `critical` property was only updating as expected on environments nested on the project resource, but was not functioning as expected on the environment resources themselves.
=> fix: set `critical` property on environment resource

.github/workflows/generate_integration_config_pr.yml, release-please-config.json
This PR removes the release please PR footer because this is also getting copied to our releases (we do not want this). I also updated the regenerate-integration-configs bot PRs to use semantic PR titles.
=> chore: remove release-please footer

.github/workflows/test.yml
This adds a new GHA to pull in the necessary secrets for running tests on PRs by outside collaborators. It will still require approval by an LD engineer. This should unblock #309.
---
Related Jira issue: [REL-7676: investigate and fix failing PR tests on terraform provider repo](https://launchdarkly.atlassian.net/browse/REL-7676)
=> chore: [REL-7676] github action to pull in secrets from SSM

.github/workflows/test.yml, launchdarkly/resource_launchdarkly_project_test.go
This just removes the `pull_request` trigger that had to be left in while we pushed `pull_request_target` to main.
For more information on how to build, test, and release, see the [internal provider runbook](https://launchdarkly.atlassian.net/wiki/spaces/PD/pages/3825598468/LaunchDarkly+Terraform+Provider+Runbook).
---
Related Jira issue: [REL-7676: investigate and fix failing PR tests on terraform provider repo](https://launchdarkly.atlassian.net/browse/REL-7676)
=> chore: [REL-7676] remove pull_request and update sha refs

docs/resources/custom_role.md, launchdarkly/resource_launchdarkly_custom_role.go
Since v2 of the provider was released, we have [updated the custom roles API](https://launchdarkly.com/docs/guides/teams-roles/custom-roles#expand-no-access-by-default) to default `base_permissions` to `no_access` instead of `reader`. This PR just adds a note to clarify.
Screenshot from our public docs:
---
Related Jira issue: [REL-8605: Document discrepancy in default base_role settings between UI and TF](https://launchdarkly.atlassian.net/browse/REL-8605)
=> fix: [REL-8605] add documentation note on discrepancy in default base permissions with current API version

.github/workflows/lint-pr-title.yml, .github/workflows/test.yml
* Close RCE vulnerability that was reported through Hacker1 (https://launchdarkly.atlassian.net/browse/SEC-7343)
---
Related Jira issue: [SEC-7345: Close RCE on terraform-provider-launchdarkly GHA workflows](https://launchdarkly.atlassian.net/browse/SEC-7345)
=> [SEC-7345] Resolve RCE vulnerability caused by pull_request_target GHA trigger
